services:
  - type: web
    name: se713-election-webportal
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        sync: false
